### PR TITLE
Implemented hierarchical view (under a flag) for find references.

### PR DESCRIPTION
**Pull request by solomatov**
I implemented https://github.com/microsoft/vscode/issues/81187 myself.
To make it less confusing I put it under a flag: "references.treeView", which is false by default.
See the screenshot with how it looks like in the attachment.
Screen Shot 2019-09-22 at 1 26 00 PM

### CODE REVIEW

**Comment by solomatov** [comment]
@mjbvz May I ask you to take a look at it? @jrieken who seems to be an owner of this project is on a vacation now.

**Comment by solomatov** [comment]
I wanted to create unit tests, but found out that webpack is used. Also, we don't want to ship them, with the extension. So, I decided not to work on them.

**Comment by mjbvz** [comment]
@solomatov Thanks for the PR! I'd prefer to wait until @jrieken is back though so that he can review the changes and provide feedback

**Comment by solomatov** [comment]
@mjbvz Ok. Let's wait then.

Also, may be you can help me with unit tests? Is there an example of idiomatic unit test setup for vs-code plugins? I know, you use mocha, but is there any canonical example to take a look at?

**Comment by solomatov** [comment]
I added test for model, since the behavior became quite complicated.

**Comment by jrieken** [comment]
Hm, this is very similar but also different to what the SCM viewlet is now offering (see attached screen recording below). Tho, SCM does support "compression", e.g folders with single entries are rendered as single row (see "foo/bar/bazz" and "js/lib"). 

Oct-01-2019 15-34-51


The SCM viewlet has access to more powerful API/utils that can be reused when rendering resources (see [`ResourceTree`](https://github.com/microsoft/vscode/blob/2724ca6c053585673ee9cb26527d18657a51dfa9/src/vs/base/common/resourceTree.ts#L90))

I think the better approach would be somehow reuse that resource tree logic in the tree view API so that we have to maintain less code and so that tree showing resources look and feel alike. 

/cc @joaomoreno @alexr00

**Comment by solomatov** [comment]
@jrieken That would be a perfect solution to the problem which my PR solves. Do you have plans to expose this API to extensions?

**Comment by alexr00** [comment]
No plan at the moment, but I've created an issue and added it to the backlog: https://github.com/microsoft/vscode/issues/81757

**Comment by solomatov** [comment]
@alexr00 If you need help with this, I can help doing this. I just know that the team is really concerned about API surface area, and having a special tree for resources might make it wider. Do you think it's possible to do it in the same way as normal tree is exposed to extensions?

**Comment by solomatov** [comment]
Closing it, since the probability of merging it is very low.

**Comment by alexr00** [comment]
@solomatov I'll need to take a look at how it's done for SCM and see how we can generalize this.

**Pull request closed without merging**
